version: '3.3'
services:
  backend:
    env_file:
      - env-couchbase.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - FSFB_PRIVATE_KEY=${BIGDATA_PRIVATE_KEY}